### ISSUE TITLE
go 1.20+ breaks when used as toolchain

### ISSUE THREAD

**Issue by paulannetts** [thought-machine/please#2715]
### Repro:
Mac AMD64 and linux AMD64, for both go 1.20 and go 1.20.1.
go 1.19.6 works as expected.

Create new please repository using `plz init`, update .plzconfig to:
```
[please]
version = 16.27.3

[go]
gotool = //third_party/go:toolchain|go
```

Create 3rd party go BUILD file
```
package(default_visibility = ["PUBLIC"])

go_toolchain(
    name = "toolchain",
    version = "1.20.1",
)

go_module(
    name = "statsd",
    install = ["statsd"],
    module = "github.com/DataDog/datadog-go/v5",
    version = "v5.0.2",
)
```

Run `plz build //third_party/go:statsd`

**Expected:** downloads go toolchain, and builds the go module.
**Actual:** error with the internal go toolchain

```
Error building target //third_party/go:_statsd#a_rule: exit status 1
find: [...]/plz-out/bin/third_party/go/toolchain/pkg/darwin_amd64: No such file or directory
```

**Comment by Tatskaari** [comment]
We've implemented this in the new [go plugin](https://github.com/please-build/go-rules), which will be the default in v17. You can migrate to use this by running `plz init plugin go`.  

Alternatively you can add this to your shell env to get the old rules to work:
```
GODEBUG="installgoroot=all"
```
You'll also have to update your `.plzconfig`:
```
[Build]
PassEnv = GODEBUG
```

**Comment by paulannetts** [comment]
Thanks - I'll try that. I'm still seeing some issues with the plugin though on plz 17.0.0-beta.3 on Mac.

Looks like it's using a brew version of go rather than the toolchain one.
```
> plz build //third_party/go:statsd
Build stopped after 160ms. 1 target failed:
    //third_party/go:_statsd#a_rule
Error building target //third_party/go:_statsd#a_rule: exit status 1
find: /usr/local/Cellar/go/1.20.1/libexec/pkg/darwin_amd64: No such file or directory
```

**Comment by Tatskaari** [comment]
By the way, you don't need to use v17 to use plugins. Your config options should have been migrated automatically. Can you show your `.plzconfig` file, specifically the `[Plugin "go"]` section? You should have something that looks like:
```
[Plugin "go"]
Target = //plugins:go
GoTool = //third_party/go:toolchain|go
``` 

If you used to have the corresponding `[Go]` config setting, then `plz init plugin go` should have migrated that for you.

**Comment by paulannetts** [comment]
That fixes it thanks - `plz init plugin go` didn't migrate the `GoTool` part.
I was in 16.27.3 at the time, but I saw the build warning "WARNING: Plugin "go" requires Please version 17.0.0-beta.1"

.plzconfig is now the following, and this builds on 1.20.1:
```
[please]
version = 16.27.3

[parse]
preloadsubincludes = ///go//build_defs:go

[Plugin "go"]
Target = //plugins:go
GoTool = //third_party/go:toolchain|go
```
